'use client';
import { useState } from 'react';
import { Check, Clock, ShieldCheck, MapPin, Pencil, X, Truck } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Progress } from '@/components/ui/progress';
import { Badge, Responsible } from './shared';
import { useRescue } from './provider';
import { available, lifecycle, type Mission } from '@/lib/rescue/model';
export function MissionCard({ mission: m, expanded = false }: {
    mission: Mission;
    expanded?: boolean;
}) {
    const { state, act, busy, ready } = useRescue();
    const [editing, setEditing] = useState(false);
    const [objective, setObjective] = useState(m.objective);
    const [requirements, setRequirements] = useState(m.requiredResources);
    const index = lifecycle.findIndex(s => s === m.status);
    const pending = m.status === 'Awaiting approval';
    const active = ['Approved', 'Resource assigned', 'In progress'].includes(m.status);
    const nextLabel: Record<string, string> = { 'Approved': 'Assign required resources', 'Resource assigned': 'Start mission', 'In progress': 'Mark completed', 'Completed': 'Resolve mission' };
    return <article id={'mission-'+m.id} className={'panel mission-card ' + (expanded ? 'expanded' : '')}><div className="row-between"><span className="eyebrow">MISSION #{m.id}</span><Badge tone={m.priority === 'Critical' ? 'red' : 'amber'}>{m.priority}</Badge></div><h3>{m.title}</h3><p className="muted">{m.objective}</p><a className="mission-incident" href={'/incidents?incident='+encodeURIComponent(m.incidentId)}><MapPin size={15}/>{state.incidents.find(i => i.id === m.incidentId)?.title}</a><div className="mission-record-meta"><span>{m.origin==='user'?'User-report mission':'SIMULATION'}</span><time dateTime={m.createdAt}>Created {new Date(m.createdAt).toISOString().slice(0,16).replace('T',' ')+' UTC'}</time><span>Approval: {m.approvalStatus}</span><span>Destination: {state.incidents.find(i=>i.id===m.incidentId)?.location}</span></div>{<div className="user-resource-note"><span className="eyebrow">RESOURCE MATCH · SAMPLE INVENTORY</span>{Object.entries(m.requiredResources).map(([id,n])=><small key={id}>{state.resources.find(r=>r.id===id)?.type}: {n} recommended · {available(state,id)} available · {m.assignedResources[id]??0} assigned</small>)}{!Object.keys(m.requiredResources).length&&<small>No matching inventory resources were identified. A coordinator must review specialist needs.</small>}{m.specialistNeeds?.length?<p>Specialist needs: {m.specialistNeeds.join(' · ')}</p>:null}</div>}<div className="resource-chips">{Object.entries(m.requiredResources).map(([id, n]) => <span className="resource-chip" key={id}><Truck size={14}/>{n} {state.resources.find(r => r.id === id)?.type}</span>)}</div><div className="row-between mission-eta"><span><Clock size={15}/> {m.eta===null?'Not estimated':`${m.eta} min`} <small>{m.origin==='user'?'route and travel time unverified':'estimated response'}</small></span><span className="meta">{m.origin==='user'?'COORDINATOR TO CONFIRM':'SIMULATED ETA'}</span></div>{expanded && <><div className="route-box"><span className="eyebrow">{m.origin==='user'?'PROPOSED WAYPOINTS · NOT A NAVIGABLE ROUTE':'SUGGESTED ROUTE · SCHEMATIC'}</span><p>{m.route.join(' → ')}</p></div><div className="lifecycle" aria-label={`Mission lifecycle: ${m.status}`}>{lifecycle.map((s, i) => <div key={s} className={i <= index ? 'done' : ''}><span>{i < index ? <Check size={12}/> : i + 1}</span><small>{s}</small></div>)}</div><Progress value={Math.max(0, index) / 6 * 100} className="mission-progress"/></>}
 <div className={'approval ' + (active ? 'active' : '')}><ShieldCheck size={18}/><div><strong>{pending ? 'HUMAN APPROVAL REQUIRED' : active ? 'MISSION ACTIVE' : m.status.toUpperCase()}</strong><small>{pending ? 'AI recommendation · no action taken' : active ? m.status === 'Approved' ? 'Approved · awaiting resource assignment' : m.status : 'Progress saved'}</small></div></div>
 <div className="mission-buttons">{pending ? <><button className="btn primary" disabled={busy || !ready} onClick={() => act({ type: 'approve', id: m.id })}><Check size={16}/>Approve Mission</button><button className="btn subtle" disabled={busy || !ready} onClick={() => { setObjective(m.objective); setRequirements(m.requiredResources); setEditing(true); }}><Pencil size={15}/>Modify</button><button className="icon-btn reject" disabled={busy || !ready} aria-label={`Reject mission ${m.id}`} title="Reject mission" onClick={() => act({ type: 'reject', id: m.id })}><X size={17}/></button></> : nextLabel[m.status] ? <button className="btn primary" disabled={busy || !ready} onClick={() => act({ type: 'advance', id: m.id })}>{nextLabel[m.status]}</button> : <span className="muted">{m.status === 'Resolved' ? 'Response complete. Resources available for reassignment.' : 'This recommendation was rejected.'}</span>}</div>
 <Dialog open={editing} onOpenChange={setEditing}><DialogContent className="rf-dialog"><DialogTitle>Modify mission {m.id}</DialogTitle><DialogDescription>Update the objective and resource plan before approval.</DialogDescription><label className="field-label">Mission objective<textarea value={objective} onChange={e => setObjective(e.target.value)} maxLength={1000} rows={3}/></label><div className="edit-resource-grid">{state.resources.map(r => <label className="field-label" key={r.id}>{r.type}<input type="number" min={0} max={r.quantity} value={requirements[r.id] ?? 0} onChange={e => setRequirements({ ...requirements, [r.id]: Number(e.target.value) })}/></label>)}</div><button className="btn primary" disabled={busy} onClick={async () => { if (await act({ type: 'modify', id: m.id, objective, requiredResources: requirements }))
        setEditing(false); }}>Save mission plan</button><Responsible /></DialogContent></Dialog>
 </article>;
}
