'use client';
import {Activity,AlertTriangle,Boxes,Flag,Play,Radio,ShieldCheck} from 'lucide-react';
import {useRescue} from './provider';
import {Badge,Status} from './shared';
import {operations} from '@/lib/rescue/selectors';
export function Overview({run}:{run:()=>void}){
  const {state,ready,busy}=useRescue(),op=operations(state);
  const kpis=[['Active incidents',op.incidents.length,AlertTriangle,'/incidents'],['Critical incidents',op.critical.length,AlertTriangle,'/incidents?severity=Critical'],['Active missions',op.active.length,Flag,'/missions?status=Active'],['Available resources',op.free,Boxes,'/resources'],['Resources assigned',op.assigned,ShieldCheck,'/resources'],['Reports received',state.reports.length,Radio,'/reports']] as const;
  return <div className="overview-content">
    <section className="rescue-simulation-banner"><div><span className="eyebrow">ONE CONNECTED RESPONSE</span><h2>From the first report to a coordinated mission.</h2><p>Explore a fictional scenario across the same reports, incidents, missions, resources, and operational map.</p><div className="workflow-brief"><span>5 reports</span><i>→</i><span>2 incidents</span><i>→</i><span>3 missions</span><i>→</i><span>Human approval</span></div></div><div className="simulation-banner-action"><button className="btn primary large" onClick={run} disabled={!ready||busy}><Play size={19}/>{busy?'Preparing…':'RUN RESCUE SIMULATION'}</button><small>{state.simulationLoaded?'Replay the workflow · saved decisions stay intact':'Opt-in sample data · no real dispatch'}</small></div></section>
    <section className="overview-kpis" aria-label="Overall system summary">{kpis.map(([label,value,Icon,href])=><a key={label} href={href} className="overview-kpi"><div className="row-between"><span>{label}</span><Icon size={19}/></div><strong className={label==='Critical incidents'&&value>0?'red-text':''}>{value}</strong><small>{label.includes('resources')||label==='Resources assigned'?'Sample inventory units':'In this workspace'}</small></a>)}</section>
    <section className="panel system-overview"><div><span className="meta">SYSTEM</span><Status/></div><div><span className="meta">AI PROCESSING</span><strong>{busy?'Processing update':state.lastAnalysis?state.lastAnalysis.mode==='LIVE'?'Latest report: live AI':'Latest report: fallback':state.simulationLoaded?'Scenario processing complete':'Ready for reports'}</strong></div><div><span className="meta">RESOURCE AVAILABILITY</span><strong>{op.free} of {state.resources.reduce((s,r)=>s+r.quantity,0)} units free</strong></div><div><span className="meta">EMERGENCY LEVEL</span>{op.level?<Badge tone={op.level==='Critical'?'red':'amber'}>{op.level}</Badge>:<strong>No open incidents</strong>}</div></section>
    <div className="overview-two-col"><section className="panel"><div className="panel-heading"><h2>Critical incidents</h2><a className="text-link" href="/incidents">View incidents</a></div>{op.critical.slice(0,3).map(i=><a className="overview-list-row" href={'/incidents?incident='+encodeURIComponent(i.id)} key={i.id}><span className="overview-severity-dot"/><div><strong>{i.title}</strong><small>{i.location} · {i.evidence.length} supporting report{i.evidence.length===1?'':'s'}</small></div><Badge tone="red">{i.priorityScore}/100</Badge></a>)}{!op.critical.length&&<p className="summary-empty">No critical incidents currently reported.</p>}</section>
    <section className="panel"><div className="panel-heading"><h2>Active missions</h2><a className="text-link" href="/missions">View missions</a></div>{op.active.slice(0,3).map(m=><a className="overview-list-row" href={'/missions#mission-'+m.id} key={m.id}><Flag size={18}/><div><strong>{m.title}</strong><small>{state.incidents.find(i=>i.id===m.incidentId)?.location}</small></div><Badge tone="green">{m.status}</Badge></a>)}{!op.active.length&&<p className="summary-empty">{op.pending.length?`${op.pending.length} mission recommendations await human approval.`:'No active missions yet.'}</p>}</section></div>
    <section className="panel resource-snapshot"><div className="panel-heading"><h2><Activity size={18}/>Resource snapshot</h2><a className="text-link" href="/resources">Resource inventory</a></div><div className="resource-snapshot-values"><div><strong>{op.free}</strong><span>Available</span></div><div><strong>{op.assigned}</strong><span>Assigned</span></div><div><strong>—</strong><span>En route · not tracked</span></div><div><strong>—</strong><span>Unavailable · not reported</span></div></div><p className="snapshot-note">Sample planning inventory. Mission progress is tracked in the app; vehicle movement and real service availability are not connected.</p></section>
  </div>;
}
